apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: my-poc
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        # image: 570282481953.dkr.ecr.ap-south-1.amazonaws.com/rosa-poc-backend:latest
        image: {{IMAGE}}
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: my-poc
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
